import type { Client, Routine, ProgressEntry, CalendarEvent } from "./types"

export const mockClients: Client[] = [
  {
    id: "1",
    name: "Carlos Martinez",
    email: "carlos@email.com",
    phone: "+34 612 345 678",
    age: 28,
    weight: 78,
    height: 175,
    objective: "ganar-musculo",
    level: "intermedio",
    status: "active",
    notes: "Entrena 4 veces por semana. Preferencia por entrenamientos matutinos.",
    joinDate: "2024-01-15",
    lastActivity: "2024-04-14",
  },
  {
    id: "2",
    name: "Ana Garcia",
    email: "ana@email.com",
    phone: "+34 623 456 789",
    age: 32,
    weight: 62,
    height: 165,
    objective: "perder-grasa",
    level: "principiante",
    status: "active",
    injuries: "Molestia en rodilla izquierda",
    notes: "Comenzó hace 2 meses. Muy motivada.",
    joinDate: "2024-02-10",
    lastActivity: "2024-04-13",
  },
  {
    id: "3",
    name: "Miguel Rodriguez",
    email: "miguel@email.com",
    phone: "+34 634 567 890",
    age: 45,
    weight: 85,
    height: 180,
    objective: "tonificar",
    level: "avanzado",
    status: "active",
    injuries: "Hernia discal L4-L5 (controlada)",
    notes: "Atleta experimentado. Evitar ejercicios de alto impacto lumbar.",
    joinDate: "2023-06-20",
    lastActivity: "2024-04-11",
  },
  {
    id: "4",
    name: "Laura Sanchez",
    email: "laura@email.com",
    phone: "+34 645 678 901",
    age: 26,
    weight: 58,
    height: 162,
    objective: "resistencia",
    level: "intermedio",
    status: "inactive",
    notes: "Prepara media maratón. Actualmente de vacaciones.",
    joinDate: "2023-11-05",
    lastActivity: "2024-04-09",
  },
  {
    id: "5",
    name: "Pedro Gomez",
    email: "pedro@email.com",
    phone: "+34 656 789 012",
    age: 38,
    weight: 92,
    height: 182,
    objective: "perder-grasa",
    level: "principiante",
    status: "active",
    notes: "Objetivo: perder 15kg en 6 meses.",
    joinDate: "2024-03-01",
    lastActivity: "2024-04-14",
  },
  {
    id: "6",
    name: "Sofia Lopez",
    email: "sofia@email.com",
    phone: "+34 667 890 123",
    age: 24,
    weight: 55,
    height: 168,
    objective: "ganar-musculo",
    level: "intermedio",
    status: "active",
    notes: "Competidora de fitness. Preparando competición en julio.",
    joinDate: "2023-09-15",
    lastActivity: "2024-04-14",
  },
]

export const mockRoutines: Routine[] = [
  {
    id: "1",
    name: "Pecho y Triceps",
    clientId: "1",
    clientName: "Carlos Martinez",
    type: "fuerza",
    createdAt: "2024-03-01",
    updatedAt: "2024-04-10",
    days: [
      {
        id: "d1",
        name: "Dia 1 - Pecho",
        exercises: [
          { id: "e1", name: "Press de banca", sets: 4, reps: "8-10", weight: "70kg" },
          { id: "e2", name: "Press inclinado mancuernas", sets: 3, reps: "10-12", weight: "24kg" },
          { id: "e3", name: "Aperturas en polea", sets: 3, reps: "12-15", weight: "15kg" },
          { id: "e4", name: "Fondos en paralelas", sets: 3, reps: "10-12" },
        ],
      },
      {
        id: "d2",
        name: "Dia 2 - Triceps",
        exercises: [
          { id: "e5", name: "Press frances", sets: 4, reps: "10-12", weight: "25kg" },
          { id: "e6", name: "Extension en polea", sets: 3, reps: "12-15", weight: "20kg" },
          { id: "e7", name: "Fondos en banco", sets: 3, reps: "15" },
        ],
      },
    ],
  },
  {
    id: "2",
    name: "HIIT Cardio",
    clientId: "2",
    clientName: "Ana Garcia",
    type: "cardio",
    createdAt: "2024-02-15",
    updatedAt: "2024-04-08",
    days: [
      {
        id: "d3",
        name: "Circuito HIIT",
        exercises: [
          { id: "e8", name: "Burpees", sets: 4, reps: "30 seg" },
          { id: "e9", name: "Mountain climbers", sets: 4, reps: "30 seg" },
          { id: "e10", name: "Jumping jacks", sets: 4, reps: "30 seg" },
          { id: "e11", name: "Sentadillas con salto", sets: 4, reps: "30 seg" },
          { id: "e12", name: "Plancha", sets: 4, reps: "45 seg" },
        ],
      },
    ],
  },
  {
    id: "3",
    name: "Full Body",
    clientId: "3",
    clientName: "Miguel Rodriguez",
    type: "mixto",
    createdAt: "2024-01-20",
    updatedAt: "2024-04-05",
    days: [
      {
        id: "d4",
        name: "Full Body A",
        exercises: [
          { id: "e13", name: "Sentadilla", sets: 4, reps: "8-10", weight: "100kg" },
          { id: "e14", name: "Press de banca", sets: 4, reps: "8-10", weight: "80kg" },
          { id: "e15", name: "Remo con barra", sets: 4, reps: "8-10", weight: "60kg" },
          { id: "e16", name: "Press militar", sets: 3, reps: "10-12", weight: "40kg" },
        ],
      },
      {
        id: "d5",
        name: "Full Body B",
        exercises: [
          { id: "e17", name: "Peso muerto", sets: 4, reps: "6-8", weight: "120kg" },
          { id: "e18", name: "Dominadas", sets: 4, reps: "8-10" },
          { id: "e19", name: "Press inclinado", sets: 3, reps: "10-12", weight: "60kg" },
          { id: "e20", name: "Curl de biceps", sets: 3, reps: "12-15", weight: "15kg" },
        ],
      },
    ],
  },
]

export const mockProgress: ProgressEntry[] = [
  {
    id: "p1",
    clientId: "1",
    date: "2024-01-15",
    weight: 75,
    bodyFat: 18,
    measurements: { chest: 98, waist: 82, arms: 35 },
  },
  {
    id: "p2",
    clientId: "1",
    date: "2024-02-15",
    weight: 76,
    bodyFat: 17,
    measurements: { chest: 99, waist: 81, arms: 36 },
  },
  {
    id: "p3",
    clientId: "1",
    date: "2024-03-15",
    weight: 77.5,
    bodyFat: 16,
    measurements: { chest: 100, waist: 80, arms: 37 },
  },
  {
    id: "p4",
    clientId: "1",
    date: "2024-04-14",
    weight: 78,
    bodyFat: 15.5,
    measurements: { chest: 101, waist: 79, arms: 37.5 },
  },
]

export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: "ce1",
    clientId: "1",
    clientName: "Carlos Martinez",
    routineId: "1",
    routineName: "Pecho y Triceps",
    date: "2024-04-14",
    time: "09:00",
    status: "completado",
  },
  {
    id: "ce2",
    clientId: "2",
    clientName: "Ana Garcia",
    routineId: "2",
    routineName: "HIIT Cardio",
    date: "2024-04-14",
    time: "11:00",
    status: "en-progreso",
  },
  {
    id: "ce3",
    clientId: "3",
    clientName: "Miguel Rodriguez",
    routineId: "3",
    routineName: "Full Body",
    date: "2024-04-14",
    time: "14:00",
    status: "pendiente",
  },
  {
    id: "ce4",
    clientId: "5",
    clientName: "Pedro Gomez",
    routineId: "2",
    routineName: "HIIT Cardio",
    date: "2024-04-15",
    time: "10:00",
    status: "pendiente",
  },
  {
    id: "ce5",
    clientId: "6",
    clientName: "Sofia Lopez",
    routineId: "1",
    routineName: "Pecho y Triceps",
    date: "2024-04-15",
    time: "16:00",
    status: "pendiente",
  },
]
